# Generated by Django 3.2.6 on 2021-08-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(max_length=50)),
                ('str_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(choices=[('new', 'new'), ('developed', 'developed'), ('tested', 'tested'), ('deployed', 'deployed')], max_length=50)),
                ('str_code', models.CharField(max_length=50)),
                ('int_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(max_length=50)),
                ('int_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_title', models.CharField(max_length=300)),
                ('txt_descrption', models.TextField()),
                ('jsn_attachment', models.JSONField(blank=True, null=True)),
                ('dat_created', models.DateField(auto_now_add=True)),
                ('int_active', models.IntegerField(default=0)),
                ('fk_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.projectmodel')),
                ('fk_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.worktypemodel')),
                ('fk_work_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.workstatusmodel')),
            ],
        ),
    ]
